name: auto merge

on:
  pull_request:
    branches: [master]

permissions:
  contents: write
  pull-requests: write

jobs:
  squash-to-master:
    runs-on: ubuntu-latest
    if: ${{ contains(fromJson('["dependabot[bot]", "github-actions[bot]"]'), github.actor) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Squash to master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{github.event.pull_request.html_url}}
        run: |
          echo "merging ${PR_URL}"
          gh pr merge "$PR_URL" --squash --delete-branch
