name: Auto-merge Dependency PRs

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'app/dependabot'
    steps:
      - name: Squash to master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{github.event.pull_request.url}}
        run: |
          echo "merging ${PR_URL}"
          gh pr merge "$PR_URL" --squash --delete-branch
